###
GET http://localhost:8080/api/user?page=0&size=5
###
GET http://localhost:8080/api/user/username?page=0&size=5
###
GET http://localhost:8080/api/user/username2?page=0&size=5
###
GET http://localhost:8080/api/user/username3?page=0&size=5
###